### PR TITLE
Add column Site Language to wp-admin/network/sites.php

### LINKED ISSUE #92: Add a column "Language" to the network site table
The language of a site should be visible (and maybe editable) on `wp-admin/network/sites.php` and `wp-admin/my-sites.php`.

### PR DESCRIPTION
**Pull request by lukashruby**
Resolves #92

### CODE REVIEW

**Comment by bueltge** [comment]
Thanks a lot for your help! We will check this in the next days and format for our codex. 
Best regards

**Comment by tfrommen** [comment]
Hi there, and thanks a lot for the PR. There are a few things to do here, though.

First of all, this should be a separate feature. Please create a new file `feature.language_column.php` next to all the other feature files, move your code over there, and revert the `feature.connection_column.php` file back to its old status.

Also, please stick to a consistent naming. (Yes, I know that MultilingualPress itself is a bad example here.) Choose _Language_ and use this term for all hooks, functions, HTML/CSS classes etc.

The `return` type is just `string` - there is no `void` return here. Yes, I know, this is wrong in the other feature file (as well).

We use spaces inside brackets, so please insert a leading and a trailing whitespace around `$lang` in your current line 77.

Please remove one of the double blank lines as well as the commented out fragment (current line 78), and add a blank line after the `return` (current line 76).

Thanks again!
Thorsten

**Comment by tfrommen** [comment]
@lukashruby are you still working on this? Do you have any problems? Just ask for help here, if you need any.

**Comment by bueltge** [comment]
@tfrommen Was fixed now, commit cc8d0618667b1fb3008b473cc725bae021c46b15
I use not the wrapper functions. I think we will delete this on long term. Is clear and more like the API, that we use the class and his method.

**Pull request closed without merging**
