### PR TITLE
[i18n] - [l10n] > new pot + French translations v.2.2.0.dev

### PR DESCRIPTION
**Pull request by fxbenard**
Hey,
just created all the necessary files for your plugin to be fully translated in French. It was definitely missing in a localisation plugin.
If you mind sending me a pro license, I'll be happy to provide you the fr-FR files for it! I guess your French customers will be more than happy to have them also!
Let me know
Cheers

### CODE REVIEW

**Comment by fxbenard** [comment]
Hey guys any news on that? thanks to let me know

**Comment by bueltge** [comment]
@fxbenard Thanks a lot for your help! Sorry for waiting. We have discussed about the possibilitie son github. Currently we managed our translations via glotpress on translate.marketpress.com/projects .

But I think your request is helpful and the copy, correction to our glotpress is our todo.

**Comment by fxbenard** [comment]
@bueltge Great if it helps. Any chance to get a pro license to test it out, thanks. Thinking to use your plugin with a WP-Translations project ;)

**Comment by bueltge** [comment]
@fxbenard Use the master branch, that is the premium version on technical view. Only the difference on support is our pro license. We work currently on a merge of the old pro and the free version. On wp.org is currently the "old" free version, but we update this later to the premium version. We will no difference in features and code, all is the same. But it is possible to pay for a premium support.

**Comment by fxbenard** [comment]
@bueltge Thanks for the confirmation. Works like a charm. Great plugin

**Pull request merged**
